### ISSUE TITLE
最新的turms-client-swift 登录超时

### ISSUE THREAD

**Issue by wushuangys** [turms-im/turms#1135] opened 2023-02-20 09:43 UTC
1. 下载的turms-client-swift 库，链上后登录 code 102 超时，尝试很多次
2. 用去年中旬保存的库是可以登录，但那个库又有其它问题
3. 这个最新的库希望改一下，并测试下管理员撤回其它成员发的消息是否可行

![截屏2023-02-20 17 41 42](https://user-images.githubusercontent.com/24885821/220069710-d75e9699-19bd-48d1-94e6-4ab23e7e7608.png)

**Comment by JamesChenX** [comment] 2023-02-20 10:08
Thanks for reporting.

It's true that I don't have too much effort for turms-client-swift honestly, especially I don't like MacOS and Xcode personally, hhh.

I will check the problem later because I have been busy recently and don't have the effort to investigate.
But I will check it once I am available, and it will be fixed next month if it's really a bug.

I will @at you when the problem is resolved.

**Comment by JamesChenX** [comment] 2023-02-28 08:38
I have tested with the latest branch `develop` and `master`, and it works.
1. I don't have the timeout problem. You can check whether you are connecting to a connectable turms-gateway. By default, the client will try to connect to `127.0.0.1:11510`
2. ...
3. It works, and when a client recalls a message, the recipient client should recall the received messages when it receives the recall notification by itself.

**Comment by wushuangys** [comment] 2023-03-01 06:21
您好，这个问题还是存在，在develop 和 master 分支都可以正常建立连接， 但登录显示超时 102，用之前带有Starscream 版本是可以正常登录

**Comment by JamesChenX** [comment] 2023-03-01 06:56
Can you help to debug turms-client-swift on your local machine when you are available? 

If you are sure that you use the latest code for servers and turms-client-swift, I cannot imagine what's happened because it works fine on my computers.
**Bug debug can figure out what happened**. So I suggest the following 5 debug steps that show how turms-client-swift receives TCP and parse it to `TurmsNotification`, and then calls the request callback.
You can give it a try and know why the timeout happens:

![image](https://user-images.githubusercontent.com/44962329/222064688-4ad1679e-b819-46fc-9e3d-31fcf341ce61.png)

![image](https://user-images.githubusercontent.com/44962329/222065692-43b3b1a7-ac27-46e7-86b1-9a68f6b47c1b.png)

**Comment by JamesChenX** [comment] 2023-03-02 07:36
Thanks for reporting.
The bug has been fixed, and you can pull the latest code from `develop` or `master`, or the latest docker images to get a try.

> 感谢您的建议，我想应该是客户端与服务端代码版本不一致的问题，现在我们在本地使用Docker搭建最新版本服务端turms，可正常的访问用户管理，但无法添加用户 ![截屏2023-03-02 13 56 25](https://user-images.githubusercontent.com/24885821/222344317-d281aee3-97ab-4bce-8830-77cc6b1f8175.png)

**Closed** 2023-03-02 07:37 UTC

**Comment by wushuangys** [comment] 2023-03-02 12:56
您好，现在发现有其它问题，群的权限是 ACCEPT_ANY_REQUEST,  使用turms-client-swift 加入群组显示成功后，查询群历史消息显示 code 5300 （不是群成员）

**Comment by JamesChenX** [comment] 2023-03-02 13:02
@wushuangys Could you help create a new issue with your problem so that we don't mix too many problems in one issue? Thanks.

**Comment by wushuangys** [comment] 2023-03-03 01:04
> @wushuangys您能否帮助创建一个新问题，这样我们就不会在一个问题中混合太多问题？谢谢。

好的，已经创建了新问题
