### ISSUE TITLE
turms admin 更新用户失败

### ISSUE THREAD

**Issue by reubencharles1007** [turms-im/turms#1315] opened 2023-10-14 08:10 UTC
<img width="1475" alt="image" src="https://github.com/turms-im/turms/assets/144759313/f1d1380a-cc7d-4930-9791-d5777aef053e">

**Comment by JamesChenX** [comment] 2023-10-14 09:37
Duplicate of https://github.com/turms-im/turms/issues/1314

**Closed by JamesChenX** 2023-10-14 09:37 UTC
